/**
 * Firebird sema tanimlari.
 * Her ifade tek tek calistirilir; nesne RDB$ tablolarinda zaten varsa atlanir.
 * Metin alanlari VARCHAR (UTF8) — BLOB kullanilmadi, boylece surucu
 * tarafinda blob okuma karmasikligi yok. Sayfa basina 8000 karakter.
 */

export const DDL: string[] = [
  // ---------------------------------------------------------------- generatorler
  `CREATE GENERATOR GEN_PL_GOREV`,
  `CREATE GENERATOR GEN_PL_UYARI`,
  `CREATE GENERATOR GEN_PL_ETIKET`,
  `CREATE GENERATOR GEN_PL_NOT`,
  `CREATE GENERATOR GEN_PL_STICKY`,
  `CREATE GENERATOR GEN_PL_SAYFA`,
  `CREATE GENERATOR GEN_PL_CIKARTMA`,

  // ---------------------------------------------------------------- tablolar
  `CREATE TABLE PL_GOREV (
     ID             INTEGER      NOT NULL,
     BASLIK         VARCHAR(300) NOT NULL,
     DETAY          VARCHAR(4000),
     BASLANGIC      TIMESTAMP    NOT NULL,
     BITIS          TIMESTAMP,
     TUM_GUN        SMALLINT     DEFAULT 0 NOT NULL,
     ONCELIK        SMALLINT     DEFAULT 1 NOT NULL,
     DURUM          SMALLINT     DEFAULT 0 NOT NULL,
     RENK           VARCHAR(20),
     TEKRAR_TIP     VARCHAR(10)  DEFAULT 'YOK' NOT NULL,
     TEKRAR_ARALIK  INTEGER      DEFAULT 1 NOT NULL,
     TEKRAR_BITIS   DATE,
     SERI_ID        INTEGER,
     TAMAMLANMA     TIMESTAMP,
     OLUSTURMA      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
     GUNCELLEME     TIMESTAMP,
     CONSTRAINT PK_PL_GOREV PRIMARY KEY (ID)
   )`,

  `CREATE TABLE PL_UYARI (
     ID          INTEGER   NOT NULL,
     GOREV_ID    INTEGER   NOT NULL,
     DK_ONCE     INTEGER   NOT NULL,
     GONDERILDI  SMALLINT  DEFAULT 0 NOT NULL,
     GONDERIM    TIMESTAMP,
     CONSTRAINT PK_PL_UYARI PRIMARY KEY (ID)
   )`,

  `CREATE TABLE PL_ETIKET (
     ID    INTEGER     NOT NULL,
     AD    VARCHAR(60) NOT NULL,
     RENK  VARCHAR(20) DEFAULT '#d9a441' NOT NULL,
     CONSTRAINT PK_PL_ETIKET PRIMARY KEY (ID),
     CONSTRAINT UQ_PL_ETIKET UNIQUE (AD)
   )`,

  `CREATE TABLE PL_GOREV_ETIKET (
     GOREV_ID   INTEGER NOT NULL,
     ETIKET_ID  INTEGER NOT NULL,
     CONSTRAINT PK_PL_GOREV_ETIKET PRIMARY KEY (GOREV_ID, ETIKET_ID)
   )`,

  `CREATE TABLE PL_NOT (
     ID          INTEGER       NOT NULL,
     TARIH       DATE          NOT NULL,
     ICERIK      VARCHAR(8000),
     RUH_HALI    VARCHAR(30),
     GUNCELLEME  TIMESTAMP,
     CONSTRAINT PK_PL_NOT PRIMARY KEY (ID),
     CONSTRAINT UQ_PL_NOT UNIQUE (TARIH)
   )`,

  `CREATE TABLE PL_STICKY (
     ID         INTEGER       NOT NULL,
     ICERIK     VARCHAR(2000),
     RENK       VARCHAR(20)   DEFAULT '#fdf08a' NOT NULL,
     KONUM_X    INTEGER       DEFAULT 40 NOT NULL,
     KONUM_Y    INTEGER       DEFAULT 40 NOT NULL,
     EGIM       INTEGER       DEFAULT 0 NOT NULL,
     Z_SIRA     INTEGER       DEFAULT 1 NOT NULL,
     OLUSTURMA  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
     CONSTRAINT PK_PL_STICKY PRIMARY KEY (ID)
   )`,

  `CREATE TABLE PL_SAYFA (
     ID          INTEGER       NOT NULL,
     BASLIK      VARCHAR(200)  NOT NULL,
     ICERIK      VARCHAR(8000),
     OZEL        SMALLINT      DEFAULT 0 NOT NULL,
     SIRA        INTEGER       DEFAULT 0 NOT NULL,
     OLUSTURMA   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
     GUNCELLEME  TIMESTAMP,
     CONSTRAINT PK_PL_SAYFA PRIMARY KEY (ID)
   )`,

  `CREATE TABLE PL_CIKARTMA (
     ID         INTEGER      NOT NULL,
     BAGLAM     VARCHAR(80)  NOT NULL,
     TUR        VARCHAR(30)  NOT NULL,
     KONUM_X    INTEGER      DEFAULT 40 NOT NULL,
     KONUM_Y    INTEGER      DEFAULT 40 NOT NULL,
     BOYUT      INTEGER      DEFAULT 72 NOT NULL,
     ACI        INTEGER      DEFAULT 0 NOT NULL,
     Z_SIRA     INTEGER      DEFAULT 1 NOT NULL,
     OLUSTURMA  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
     CONSTRAINT PK_PL_CIKARTMA PRIMARY KEY (ID)
   )`,

  // ---------------------------------------------------------------- triggerlar
  `CREATE TRIGGER PL_GOREV_BI FOR PL_GOREV ACTIVE BEFORE INSERT POSITION 0 AS
   BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_PL_GOREV, 1); END`,

  `CREATE TRIGGER PL_UYARI_BI FOR PL_UYARI ACTIVE BEFORE INSERT POSITION 0 AS
   BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_PL_UYARI, 1); END`,

  `CREATE TRIGGER PL_ETIKET_BI FOR PL_ETIKET ACTIVE BEFORE INSERT POSITION 0 AS
   BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_PL_ETIKET, 1); END`,

  `CREATE TRIGGER PL_NOT_BI FOR PL_NOT ACTIVE BEFORE INSERT POSITION 0 AS
   BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_PL_NOT, 1); END`,

  `CREATE TRIGGER PL_STICKY_BI FOR PL_STICKY ACTIVE BEFORE INSERT POSITION 0 AS
   BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_PL_STICKY, 1); END`,

  `CREATE TRIGGER PL_SAYFA_BI FOR PL_SAYFA ACTIVE BEFORE INSERT POSITION 0 AS
   BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_PL_SAYFA, 1); END`,

  `CREATE TRIGGER PL_CIKARTMA_BI FOR PL_CIKARTMA ACTIVE BEFORE INSERT POSITION 0 AS
   BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_PL_CIKARTMA, 1); END`,

  // ---------------------------------------------------------------- indeksler
  `CREATE INDEX IX_PL_GOREV_BAS ON PL_GOREV (BASLANGIC)`,
  `CREATE INDEX IX_PL_GOREV_DURUM ON PL_GOREV (DURUM)`,
  `CREATE INDEX IX_PL_UYARI_GOREV ON PL_UYARI (GOREV_ID)`,
  `CREATE INDEX IX_PL_GE_ETIKET ON PL_GOREV_ETIKET (ETIKET_ID)`,
  `CREATE INDEX IX_PL_CIKARTMA_BAGLAM ON PL_CIKARTMA (BAGLAM)`
]

/** Ilk kurulumda eklenen ornek etiketler. */
export const SEED: string[] = [
  `INSERT INTO PL_ETIKET (AD, RENK) VALUES ('İş', '#7d9a72')`,
  `INSERT INTO PL_ETIKET (AD, RENK) VALUES ('Kişisel', '#c06c52')`,
  `INSERT INTO PL_ETIKET (AD, RENK) VALUES ('Müşteri', '#4f7d9e')`,
  `INSERT INTO PL_ETIKET (AD, RENK) VALUES ('Fatura', '#7e5a7b')`
]
